title: Hooshvare Lab
email: research@hooshvare.com
description: >- # this means to ignore newlines until "baseurl:"
  Founded in 2020, Hooshvare team consists of young AI enthusiasts who seek to empower the AI scientific 
  community. Hooshvare strives to produce and provide rich scientific and educational material to individuals 
  as well as organizations with an interdisciplinary mindset.
# baseurl: "/"
# url: "https://hooshvare.github.io"
twitter_username: hooshvare
github_username:  hooshvare

# Build settings
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed

#  Extra configs
footer_content: "Copyright &copy; 2020-2021 Hooshvare Research Lab."
permalink: pretty
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
color_scheme: nil

aux_links:
  "Hooshvare Lab":
    - "//github.com/hooshvare/hooshvare.github.io"

# exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false